//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sharpdown.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sharpdown.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body {
        ///  font-family: Helvetica, arial, sans-serif;
        ///  font-size: 14px;
        ///  line-height: 1.6;
        ///  padding-top: 10px;
        ///  padding-bottom: 10px;
        ///  background-color: white;
        ///  padding: 30px; }
        ///
        ///body &gt; *:first-child {
        ///  margin-top: 0 !important; }
        ///body &gt; *:last-child {
        ///  margin-bottom: 0 !important; }
        ///
        ///a {
        ///  color: #4183C4; }
        ///a.absent {
        ///  color: #cc0000; }
        ///a.anchor {
        ///  display: block;
        ///  padding-left: 30px;
        ///  margin-left: -30px;
        ///  cursor: pointer;
        ///  position: absolute;
        ///  top: 0;
        ///  left: 0;
        ///  bottom: 0; }
        ///
        ///h1, h2, h3, h4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DocumentStyle {
            get {
                return ResourceManager.GetString("DocumentStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* http://prismjs.com/download.html?themes=prism&amp;languages=markup+css+clike+javascript+abap+actionscript+apacheconf+apl+applescript+asciidoc+aspnet+autoit+autohotkey+bash+basic+batch+c+brainfuck+bro+bison+csharp+cpp+coffeescript+ruby+css-extras+d+dart+diff+docker+eiffel+elixir+erlang+fsharp+fortran+gherkin+git+glsl+go+groovy+haml+handlebars+haskell+haxe+http+icon+inform7+ini+j+jade+java+json+julia+keyman+kotlin+latex+less+lolcode+lua+makefile+markdown+matlab+mel+mizar+monkey+nasm+nginx+nim+nix+nsis+objectiv [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HighlightStyle {
            get {
                return ResourceManager.GetString("HighlightStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* http://prismjs.com/download.html?themes=prism&amp;languages=markup+css+clike+javascript+abap+actionscript+apacheconf+apl+applescript+asciidoc+aspnet+autoit+autohotkey+bash+basic+batch+c+brainfuck+bro+bison+csharp+cpp+coffeescript+ruby+css-extras+d+dart+diff+docker+eiffel+elixir+erlang+fsharp+fortran+gherkin+git+glsl+go+groovy+haml+handlebars+haskell+haxe+http+icon+inform7+ini+j+jade+java+json+julia+keyman+kotlin+latex+less+lolcode+lua+makefile+markdown+matlab+mel+mizar+monkey+nasm+nginx+nim+nix+nsis+objectiv [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HightlightScript {
            get {
                return ResourceManager.GetString("HightlightScript", resourceCulture);
            }
        }
    }
}
